initial gcc

diff --git a/infra/gcc/Dockerfile b/infra/gcc/Dockerfile
--- a/infra/gcc/Dockerfile
+++ b/infra/gcc/Dockerfile
@@ -1,6 +1,8 @@
 FROM ubuntu:latest
 
-# Install crosstool-ng dependencies
+# ==========================
+# || Install Dependencies ||
+# ==========================
 RUN apt update && \
     DEBIAN_FRONTEND=noninteractive apt install -y \
         build-essential \
@@ -22,7 +24,9 @@ RUN apt update && \
         curl \
         sudo
 
-# Build and install crosstool-ng
+# ========================
+# || Build crosstool-ng ||
+# ========================
 RUN git clone https://github.com/crosstool-ng/crosstool-ng /opt/crosstool-ng
 WORKDIR /opt/crosstool-ng
 RUN ./bootstrap && \
@@ -30,27 +34,58 @@ RUN ./bootstrap && \
     make && \
     make install
 
-# Create user 
+# ================
+# || Create User||
+# ================
 RUN useradd -m -s /bin/bash builder && \
     usermod -aG sudo builder
 RUN echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
 USER builder
 WORKDIR /home/builder
 
-# Configure the toolchain
+# ============================
+# || Configure crosstool-ng ||
+# ============================
 ARG libc=gnu
 ARG libc_version
-ARG cpp=yes
-# ARG static=no
+ARG gcc_version=15
+ARG rebuild_id=1
+
+# Standard configs
 RUN echo 'CT_CONFIG_VERSION="4"' > defconfig && \
     echo 'CT_ARCH_X86=y' >> defconfig && \
     echo 'CT_OMIT_TARGET_VENDOR=y' >> defconfig && \
     echo 'CT_ARCH_64=y' >> defconfig && \
     echo 'CT_STATIC_TOOLCHAIN=y' >> defconfig && \
     echo 'CT_KERNEL_LINUX=y' >> defconfig && \
-    echo 'CT_CC_GCC_LNK_HASH_STYLE_BOTH=y' >> defconfig && \
-    echo '# CT_LIBC_XLDD is not set' >> defconfig
+    echo 'CT_LOG_PROGRESS_BAR=n' >> defconfig && \
+    echo 'CT_PREFIX_DIR_RO=n' >> defconfig && \
+    echo 'CT_CC_LANG_CXX=y' >> defconfig && \
+    echo 'CT_DEBUG_GDB=y' >> defconfig && \
+    echo 'CT_CC_GCC_LNK_HASH_STYLE_BOTH=y' >> defconfig
 
+# GCC version configs
+RUN if [ "$gcc_version" = "15" ]; then \
+        echo 'CT_GCC_V_15=y' >> defconfig; \
+    elif [ "$gcc_version" = "14" ]; then \
+        echo 'CT_GCC_V_14=y' >> defconfig && \
+        echo 'CT_GMP_EXTRA_CFLAGS="-std=gnu17"' >> defconfig && \
+        echo 'CT_NCURSES_EXTRA_CFLAGS="-std=gnu17"' >> defconfig; \
+    elif [ "$gcc_version" = "13" ]; then \
+        echo 'CT_GCC_V_13=y' >> defconfig && \
+        echo 'CT_GMP_EXTRA_CFLAGS="-std=gnu17"' >> defconfig && \
+        echo 'CT_NCURSES_EXTRA_CFLAGS="-std=gnu17"' >> defconfig; \
+    elif [ "$gcc_version" = "12" ]; then \
+        echo 'CT_GCC_V_12=y' >> defconfig && \
+        echo 'CT_GMP_EXTRA_CFLAGS="-std=gnu17"' >> defconfig && \
+        echo 'CT_NCURSES_EXTRA_CFLAGS="-std=gnu17"' >> defconfig; \
+    else \
+        echo "Error: Unsupported gcc_version: $gcc_version" >&2 && \
+        echo "Supported versions: 15, 14, 13, 12" >&2 && \
+        exit 1; \
+    fi
+
+# glibc configs
 RUN if [ "$libc" = "gnu" ]; then \
         echo 'CT_GLIBC_KERNEL_VERSION_NONE=y' >> defconfig; \
         if [ -n "$libc_version" ]; then \
@@ -58,6 +93,7 @@ RUN if [ "$libc" = "gnu" ]; then \
         fi; \
     fi
 
+# musl configs
 RUN if [ "$libc" = "musl" ]; then \
         echo 'CT_LIBC_MUSL=y' >> defconfig; \
         if [ -n "$libc_version" ]; then \
@@ -65,28 +101,33 @@ RUN if [ "$libc" = "musl" ]; then \
         fi; \
     fi
 
-# gdb requires c++. maybe gdb should be separated out as a build option
-RUN if [ "$cpp" = "yes" ]; then \
-        echo 'CT_CC_LANG_CXX=y' >> defconfig && \
-        echo 'CT_DEBUG_GDB=y' >> defconfig; \
-    fi
-
-# works for musl but not for glibc. fails when configuring multilib.
-# more holistically, do we care? can this be handled by suppling -static?
-# RUN if [ "$static" = "yes" ]; then \
-#         echo '# CT_SHARED_LIBS is not set' >> defconfig; \
-#     fi
-
-# Build the toolchain
+# =====================
+# || Build Toolchain ||
+# =====================
 RUN ct-ng defconfig
 RUN ct-ng build
 
-# Create tarballs of the toolchain components
-# Create bin tarball (contents of bin directory without the bin/ prefix)
-RUN cd /home/builder/x-tools/x86_64-linux-${libc} && \
-    XZ_OPT=-e9 tar cJf /home/builder/toolchain.tar.xz bin/ lib/ libexec/ share/
+# TODO: move these to toolchains_cc
+# RUN cd /home/builder/x-tools/x86_64-linux-${libc}/x86_64-linux-${libc}/sysroot/lib && \
+#     ln -s ../../../lib/gcc/ .
 
-# Create sysroot tarball (contents of sysroot directory without the sysroot/ prefix)
-RUN cd /home/builder/x-tools/x86_64-linux-${libc}/x86_64-linux-${libc}/sysroot && \
-    XZ_OPT=-e9 tar cJf /home/builder/sysroot.tar.xz *
+# RUN cd /home/builder/x-tools/x86_64-linux-${libc}/x86_64-linux-${libc}/sysroot/usr/include && \
+#     ln -s ../../../include/c++/ .
 
+# =======================
+# || Package Toolchain ||
+# =======================
+RUN gcc_full_version=$(/home/builder/x-tools/x86_64-linux-${libc}/bin/x86_64-linux-${libc}-gcc --version | head -n1 | awk '{print $NF}') && \
+    cd /home/builder/x-tools/x86_64-linux-${libc} && \
+    XZ_OPT=-e9 tar cJf /home/builder/gcc-${gcc_full_version}-x86_64-linux-${libc}-r${rebuild_id}.tar.xz \
+        bin/ \
+        libexec/ \
+        x86_64-linux-${libc}/lib/ \
+        x86_64-linux-${libc}/bin/ && \
+    XZ_OPT=-e9 tar cJf /home/builder/libgcc-${gcc_full_version}-x86_64-linux-${libc}-r${rebuild_id}.tar.xz \
+        lib/ && \
+    XZ_OPT=-e9 tar cJf /home/builder/libstdcxx-${gcc_full_version}-x86_64-linux-${libc}-r${rebuild_id}.tar.xz \
+        x86_64-linux-${libc}/include/ \
+        x86_64-linux-${libc}/lib64/ && \
+    XZ_OPT=-e9 tar cJf /home/builder/sysroot-x86_64-linux-${libc}-r${rebuild_id}.tar.xz \
+        x86_64-linux-${libc}/sysroot/
